name: Vercel Production Deployment
# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#   VITE_BASE_API: ${{ vars.VITE_BASE_API }}
on:
  push:
    branches:
      - main
jobs:
  ci-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run linters
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit

  # deploy-production:
  #   runs-on: ubuntu-latest
  #   needs: ci-production
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: yarn install
  #     - name: Install Vercel CLI
  #       run: npm install --global vercel@latest
  #     - name: Pull Vercel Environment Information
  #       run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
  #     - name: Build Project Artifacts
  #       run: vercel build --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
  #     - name: Deploy Project Artifacts to Vercel
  #       run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
